# Generated by Django 3.2.9 on 2024-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
